language: julia

julia:
 - 1.0
 - nightly

notifications:
    email: false

matrix:
  allow_failures:
  - julia: nightly

after_success:
 - julia -e 'cd(Pkg.dir("BEDMatrices")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
